language: python
python:
    - 3.5
os:
    - linux
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install doxygen
install:
    - pip3 install -r requirements.txt
script:
    - make test
    - make profile
    - make castle
    - make rock
    - make augcastle
    - make dish
    - make doxygen
