language: python
python:
    - 3.5
os:
    - linux
install:
    - apt-get install doxygen
    - pip3 install -r requirements.txt
script:
    - make test
    - make profile
    - make castle
    - make rock
    - make augcastle
    - make dish
    - make doxygen
